INSERT INTO person (
    id,
    firstName,
    lastName,
    phone,
    email,
    password,
    pin,
    city,
    neighbourhood,
    locationCoordinate,
    walletId,
    specialization,
    rating,
    accountType,
    isCustomer,
    isTrader,
    followers,
    searchTerm,
    profileImagePathLocation
  )
VALUES (
    20,
    'tapuwa',
    'greats',
    '0777757609',
    'null',
    'null',
    'null',
    'harare',
    'machipisa',
    0,
    'null',
    'skin care',
    'null',
    '',
    FALSE,
    TRUE,
    'null',
    '[greats harare machipisa skin care 0777757609]',
    'https://firebasestorage.googleapis.com/v0/b/geza-marketplace-9334d.appspot.com/o/images%2F1689759651851?alt=media&token=ba975d39-2981-447a-ac31-90cbe6adf1da'
  );