// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACFglwmVDyNUYbxjfyNmyY2n9ZWaeeZBk',
    appId: '1:535345966942:web:4faace6134ef56712fa9cf',
    messagingSenderId: '535345966942',
    projectId: 'geza-marketplace-9334d',
    authDomain: 'geza-marketplace-9334d.firebaseapp.com',
    storageBucket: 'geza-marketplace-9334d.appspot.com',
    measurementId: 'G-H7M6YVLJTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnyUQO7TiIF1tdyccF2_7Zh5rpAXrYQew',
    appId: '1:535345966942:android:274d4d43505728db2fa9cf',
    messagingSenderId: '535345966942',
    projectId: 'geza-marketplace-9334d',
    storageBucket: 'geza-marketplace-9334d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmoTFR5TganDh0aWedsGZXoeZ9Pw98fAg',
    appId: '1:535345966942:ios:ad0528d6b8bfd4a22fa9cf',
    messagingSenderId: '535345966942',
    projectId: 'geza-marketplace-9334d',
    storageBucket: 'geza-marketplace-9334d.appspot.com',
    iosClientId: '535345966942-lq8p3sgodm7r9mcf2kog4m6it0cdhaq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gezeStylist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmoTFR5TganDh0aWedsGZXoeZ9Pw98fAg',
    appId: '1:535345966942:ios:bcc53569759425e12fa9cf',
    messagingSenderId: '535345966942',
    projectId: 'geza-marketplace-9334d',
    storageBucket: 'geza-marketplace-9334d.appspot.com',
    iosClientId: '535345966942-2gr3hh2c94utnlmhpmjac75jtlgpvmrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gezeStylist.RunnerTests',
  );
}
